on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run lint
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm ci
      - run: npm test
  Build:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: pokemon-showdown-type-helper
          path: dist
  Release:
    needs:
      - Test
      - Build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: pokemon-showdown-type-helper
      - run: ls
      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: pokemon-showdown-type-helper.zip
